name: docker-push CI

on:
  push:
    # Pattern matched against refs/tags
    tags:        
    - '*'           # Push events to every tag not containing /
  
jobs:
  docker_push:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
      
      - name: build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          # options related to BUILDing the docker image:
          multiPlatform: true
          platform: linux/amd64,linux/arm64,linux/arm/v7
          image: photo-organizer
          addLatest: true
          # options related to PUSHing the docker image:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
